# Generated by Django 5.2.16 on 2026-07-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(default='', max_length=255, unique=True, verbose_name='内容ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('main_content', models.TextField(blank=True, default='', verbose_name='主要内容')),
                ('url', models.URLField(max_length=500, verbose_name='知乎链接')),
                ('hot_value', models.IntegerField(default=0, verbose_name='热度值')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '知乎热榜',
                'verbose_name_plural': '知乎热榜',
                'db_table': 'zhihu_hot_list',
                'ordering': ['-hot_value'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(db_index=True, max_length=255, verbose_name='内容ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('content', models.TextField(blank=True, default='', verbose_name='评论内容')),
                ('approve_save_comment', models.CharField(default='', max_length=255, verbose_name='点赞-收藏-评论')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='topics.topic', verbose_name='所属话题')),
            ],
            options={
                'verbose_name': '知乎评论',
                'verbose_name_plural': '知乎评论',
                'db_table': 'zhihu_comment',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TopicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('rank', models.IntegerField()),
                ('hot_value', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
        ),
    ]
