# Generated by Django 5.2.16 on 2026-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='入库时间'),
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
        migrations.DeleteModel(
            name='TopicHistory',
        ),
    ]
